services:
  - type: web
    name: fraud-detection-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        fromService:
          name: fraud-detection-ai
          type: web
          property: host
      - key: VITE_WS_URL
        fromService:
          name: fraud-detection-ai
          type: web
          property: host

  - type: web
    name: fraud-detection-ai
    env: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    envVars:
      - key: PORT
        value: 5000
      - key: MODEL_PATH
        value: /app/fraud_model.pkl
      - key: KAFKA_BOOTSTRAP_SERVERS
        fromService:
          name: fraud-detection-kafka
          type: web
          property: host

  - type: web
    name: fraud-detection-streaming
    env: docker
    dockerfilePath: ./streaming-service/Dockerfile
    dockerContext: ./streaming-service
    envVars:
      - key: PORT
        value: 8000
      - key: KAFKA_BOOTSTRAP_SERVERS
        fromService:
          name: fraud-detection-kafka
          type: web
          property: host
      - key: AI_SERVICE_URL
        fromService:
          name: fraud-detection-ai
          type: web
          property: host

  - type: web
    name: fraud-detection-kafka
    env: docker
    dockerfilePath: ./kafka/Dockerfile
    dockerContext: ./kafka
    envVars:
      - key: KAFKA_CFG_NODE_ID
        value: 1
      - key: KAFKA_CFG_PROCESS_ROLES
        value: broker,controller
      - key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: 1@kafka:9093
      - key: KAFKA_CFG_LISTENERS
        value: PLAINTEXT://:9092,CONTROLLER://:9093
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: PLAINTEXT://${RENDER_EXTERNAL_URL}:9092
      - key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        value: CONTROLLER
      - key: ALLOW_PLAINTEXT_LISTENER
        value: "yes" 