services:
  - type: web
    name: img_2023041-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: MODEL_PATH
        value: /opt/render/project/src/ai_service/fraud_model.pkl
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    autoDeploy: true

  - type: static
    name: img_2023041-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://img_2023041-1.onrender.com
      - key: VITE_WS_URL
        value: wss://img_2023041-1.onrender.com/ws 