services:
  - type: web
    name: fraud-detection-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 8000
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: kafka:9092
      - key: MODEL_PATH
        value: /app/ai_service/fraud_model.pkl
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: fraud-detection-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://fraud-detection-service.onrender.com
      - key: VITE_WS_URL
        value: wss://fraud-detection-service.onrender.com 