FROM bitnami/kafka:latest

# Set environment variables
ENV ALLOW_PLAINTEXT_LISTENER=yes
ENV KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

# Expose Kafka port
EXPOSE 9092

# Use the default entrypoint and cmd from the base image 